import PyInstaller.__main__
import os

# 获取当前脚本所在目录的绝对路径
base_path = os.path.dirname(os.path.abspath(__file__))
# 获取图标文件的绝对路径
icon_path = os.path.join(base_path, 'src', 'icon.ico')

PyInstaller.__main__.run([
    os.path.join(base_path, 'src', 'calculator_qt.py'),
    '--onefile',
    '--windowed',
    '--name=数字计算器Qt',
    f'--icon={icon_path}',
    '--add-binary', f'{icon_path};.',
    '--clean',
    '--upx-dir=upx',
    '--upx-exclude=vcruntime140.dll',
    '--optimize=2',
    '--hidden-import=PyQt6.QtCore',
    '--hidden-import=PyQt6.QtGui',
    '--hidden-import=PyQt6.QtWidgets',
    '--exclude-module=matplotlib',
    '--exclude-module=numpy',
    '--exclude-module=PIL',
    '--exclude-module=pandas',
    '--exclude-module=scipy',
    '--exclude-module=PyQt6.QtNetwork',
    '--exclude-module=PyQt6.QtQml',
    '--exclude-module=PyQt6.QtQuick',
    '--exclude-module=PyQt6.QtSql',
    '--exclude-module=PyQt6.QtTest',
    '--exclude-module=PyQt6.QtXml',
    '--exclude-module=unittest',
    '--exclude-module=pydoc',
    '--exclude-module=doctest',
    '--exclude-module=distutils',
    '--exclude-module=xml',
    '--exclude-module=http',
    '--exclude-module=html',
    '--exclude-module=pdb',
    '--exclude-module=pkg_resources',
    '--exclude-module=multiprocessing',
    '--exclude-module=asyncio',
    '--exclude-module=concurrent',
    '--exclude-module=ctypes',
    '--exclude-module=curses',
    '--exclude-module=dbm',
    '--exclude-module=lib2to3',
    '--exclude-module=OpenGL',
    '--exclude-module=pydoc_data',
    '--exclude-module=pywin',
    '--exclude-module=win32com',
    '--exclude-module=win32api',
    '--exclude-module=direct',
    '--exclude-module=tcl',
    '--exclude-module=tk',
    '--exclude-module=_tkinter',
    '--exclude-module=tkinter',
    '--upx-opts=--best --lzma',
    '--specpath=build',
    '--distpath=dist',
    '--workpath=build',
    '--disable-windowed-traceback'
]) 